name: CI

on: [push, pull_request]

jobs:
  py310:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        toxenv: [pyqt515, debug]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up python 3.10
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 libexiv2-dev
        sudo apt-get install build-essential g++ python-dev autotools-dev libicu-dev libbz2-dev

        python --version
        pwd

        wget -O boost_1_78_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.gz/download
        tar xf boost_1_78_0.tar.gz
        cd boost_1_78_0
        mkdir install
        ./bootstrap.sh --prefix=install
        sudo ./b2 --with=all install

        ls install/lib

        python -m pip install --upgrade pip
        pip install tox

    - name: Test with tox
      run: |
        export LD_LIBRARY_PATH=boost_1_78_0/install/lib:$LD_LIBRARY_PATH
        tox -e ${{ matrix.toxenv }}
      env:
        CI: Github-Actions
